%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/taller-dis1/ESU1_beta_IQ.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/24 11:13:29

%% Initialize variables.
filename = '/home/taller-dis1/ESU1_beta_IQ.dat';
delimiter = ' ';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TIME = dataArray{:, 1};
CFE = dataArray{:, 2};
DIGITAL = dataArray{:, 3};
CH0I = dataArray{:, 4};
CH0Q = dataArray{:, 5};
CH1I = dataArray{:, 6};
CH1Q = dataArray{:, 7};
CH2I = dataArray{:, 8};
CH2Q = dataArray{:, 9};
CH3I = dataArray{:, 10};
CH3Q = dataArray{:, 11};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;