function [TIME,CFE,DIGITAL,CH0I,CH0Q,CH1I,CH1Q,CH2I,CH2Q,CH3I,CH3Q] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,CFE,DIGITAL,CH0I,CH0Q,CH1I,CH1Q,CH2I,CH2Q,CH3I,CH3Q] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [TIME,CFE,DIGITAL,CH0I,CH0Q,CH1I,CH1Q,CH2I,CH2Q,CH3I,CH3Q] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [TIME,CFE,DIGITAL,CH0I,CH0Q,CH1I,CH1Q,CH2I,CH2Q,CH3I,CH3Q] = importfile('ESU1_beta_IQ.dat',1, 5676228);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/10/24 11:12:53

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TIME = dataArray{:, 1};
CFE = dataArray{:, 2};
DIGITAL = dataArray{:, 3};
CH0I = dataArray{:, 4};
CH0Q = dataArray{:, 5};
CH1I = dataArray{:, 6};
CH1Q = dataArray{:, 7};
CH2I = dataArray{:, 8};
CH2Q = dataArray{:, 9};
CH3I = dataArray{:, 10};
CH3Q = dataArray{:, 11};


